<?php

return array(
        'autocomplete' => array(
                'Lost',
                'Heroes',
                'Breaking Bad',
                'Stargate Universe',
                'Burn Notice',
                'The Ultimate Fighter',
                'MythBusters',
                'Glee',
                'FlashForward',
                '24',
                'Chuck',
                'Family Guy',
                'Legend of the Seeker',
                'Fringe',
                'Modern Family',
                'V (2009)',
                'Star Wars The Clone Wars',
                'Spartacus Blood and Sand',
                'White Collar',
                'Better Off Ted',
                'Top Gear',
                'Merlin (2008)',
                'Misfits',
                'Dexter',
                'Nitro Circus',
                'True Blood',
                'Prison Break',
                'Terminator The Sarah Connor Chronicles',
                'Stargate Atlantis',
                'Ice Road Truckers',
                'House',
                'Dead Like Me',
                'Deadliest Catch',
                'South Park',
                'Star Trek',
                'Entourage',
                'Twin Peaks',
                'Friends',
                'Buffy the Vampire Slayer',
                'The Simpsons',
                'Major',
                '30 Rock',
                '90210',
                'Bones',
                'Britains Got Talent',
                'Brothers And Sisters',
                'Californication',
                'Castle 2009',
                'Cougar Town',
                'Criminal Minds',
                'CSI',
                'CSI Miami',
                'Desperate Housewives',
                'Doctor Who',
                'Drop Dead Diva',
                'Gossip Girl',
                'Greys Anatomy',
                'How I Met Your Mother',
                'Justified',
                'NCIS',
                'One Tree Hill',
                'Royal Pains',
                'Smallville',
                'Supernatural',
                'The Big Bang Theory',
                'The Mentalist',
                'The Vampire Diaries',
                'Two And A Half Men',
                'Whale Wars',
                'WWE Friday Night Smackdown',
                'The Tudors',
                'Hells Kitchen',
                'Arga snickaren',
                'Erik & Mackan Guldfeber',
                'Draknästet',
                'Fuskbyggarna',
                'Band of Brothers',
                'Detective Conan',
                'Rome',
                'Sherlock',
                'Haven',
                'Deadwood',
                'The Wire',
                'The Corner',
                'The Shield',
                'The Sopranos',
                'The Unit',
                'The Gates',
                'The X-Files',
                'The Prisoner',
                'The Inside',
                'Mad Men',
                'Battlestar Galactica',
                'Jericho',
                'Sons of Anarchy',
                'Southland',
                'Crash',
                'Millennium',
                'Damages',
                'Third Watch',
                'Caprica',
                'Star Trek The Next Generation',
                'Star Trek Voyager',
                'In Treatment',
                'Dollhouse',
                'Coronation Street',
                'Emmerdale',
        )
);

?>
